name: training_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  invert_colors: ^0.0.4
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.2
  path_provider: ^2.0.9
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  flutter_spinkit: ^5.1.0
#  awesome_notifications: ^0.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0


flutter:
  assets:
    - images/
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
        - asset: fonts/Raleway/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway/Raleway-Light.ttf
        - asset: fonts/Raleway/Raleway-Medium.ttf
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
        - asset: fonts/Raleway/Raleway-Thin.ttf


